basePath: /
definitions:
  dto.ErrorRes:
    properties:
      errors: {}
      message:
        example: "no"
        type: string
      success:
        example: false
        type: boolean
    type: object
  dto.PathData:
    properties:
      grpc:
        type: string
      upgrade:
        type: string
      ws:
        type: string
    type: object
  dto.PayloadWSData:
    properties:
      payloadcdn:
        type: string
      payloadwithpath:
        type: string
    type: object
  dto.PortData:
    properties:
      none:
        items:
          type: string
        type: array
      tls:
        items:
          type: string
        type: array
      udpgw:
        items:
          type: string
        type: array
    type: object
  dto.SSHData:
    properties:
      city:
        example: Jakarta
        type: string
      expired:
        example: "2006-01-02 15:04:05"
        type: string
      hostname:
        example: domain.com
        type: string
      isp:
        example: Neko Tunneling ltd
        type: string
      password:
        example: neko123
        type: string
      payload_ws:
        $ref: '#/definitions/dto.PayloadWSData'
      port:
        $ref: '#/definitions/dto.PortData'
      username:
        example: neko123
        type: string
    type: object
  dto.SuccessRes:
    properties:
      data: {}
      message:
        example: ok
        type: string
      success:
        example: true
        type: boolean
    type: object
  dto.TrojanData:
    properties:
      city:
        example: Jakarta
        type: string
      expired:
        example: "2006-01-02 15:04:05"
        type: string
      hostname:
        example: domain.com
        type: string
      isp:
        example: Neko Tunneling ltd
        type: string
      link:
        $ref: '#/definitions/dto.XrayLinkData'
      password:
        example: neko123
        type: string
      path:
        $ref: '#/definitions/dto.PathData'
      port:
        $ref: '#/definitions/dto.PortData'
      username:
        example: neko123
        type: string
    type: object
  dto.VlessData:
    properties:
      city:
        example: Jakarta
        type: string
      expired:
        example: "2006-01-02 15:04:05"
        type: string
      hostname:
        example: domain.com
        type: string
      isp:
        example: Neko Tunneling ltd
        type: string
      link:
        $ref: '#/definitions/dto.XrayLinkData'
      password:
        example: neko123
        type: string
      path:
        $ref: '#/definitions/dto.PathData'
      port:
        $ref: '#/definitions/dto.PortData'
      username:
        example: neko123
        type: string
    type: object
  dto.VmessData:
    properties:
      city:
        example: Jakarta
        type: string
      expired:
        example: "2006-01-02 15:04:05"
        type: string
      hostname:
        example: domain.com
        type: string
      isp:
        example: Neko Tunneling ltd
        type: string
      link:
        $ref: '#/definitions/dto.XrayLinkData'
      password:
        example: neko123
        type: string
      path:
        $ref: '#/definitions/dto.PathData'
      port:
        $ref: '#/definitions/dto.PortData'
      username:
        example: neko123
        type: string
    type: object
  dto.XrayLinkData:
    properties:
      grpc:
        type: string
      none:
        type: string
      tls:
        type: string
      upnone:
        type: string
      uptls:
        type: string
    type: object
info:
  contact: {}
  description: Selamat datang di dokumentasi Neko Tunneling API
  title: Neko Tunneling API
  version: "1.0"
paths:
  /vps/trial/ssh:
    post:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: Durasi Trial (Menit, maks 1440)
        in: formData
        name: expired
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Berhasil membuat akun trial SSH
          schema:
            allOf:
            - $ref: '#/definitions/dto.SuccessRes'
            - properties:
                data:
                  $ref: '#/definitions/dto.SSHData'
              type: object
        "400":
          description: Bad Request - Payload body tidak valid
          schema:
            $ref: '#/definitions/dto.ErrorRes'
        "422":
          description: Unprocessable Entity - Validasi form gagal
          schema:
            $ref: '#/definitions/dto.ErrorRes'
        "500":
          description: Internal Server Error - Gagal eksekusi ke server
          schema:
            $ref: '#/definitions/dto.ErrorRes'
      security:
      - BearerAuth: []
      summary: Trial Akun SSH
      tags:
      - Trial Akun
  /vps/trial/trojan:
    post:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: Durasi Trial (Menit, maks 1440)
        in: formData
        name: expired
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Berhasil membuat akun trial Trojan
          schema:
            allOf:
            - $ref: '#/definitions/dto.SuccessRes'
            - properties:
                data:
                  $ref: '#/definitions/dto.TrojanData'
              type: object
        "400":
          description: Bad Request - Payload body tidak valid
          schema:
            $ref: '#/definitions/dto.ErrorRes'
        "422":
          description: Unprocessable Entity - Validasi form gagal
          schema:
            $ref: '#/definitions/dto.ErrorRes'
        "500":
          description: Internal Server Error - Gagal eksekusi ke server
          schema:
            $ref: '#/definitions/dto.ErrorRes'
      security:
      - BearerAuth: []
      summary: Trial Akun Trojan
      tags:
      - Trial Akun
  /vps/trial/vless:
    post:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: Durasi Trial (Menit, maks 1440)
        in: formData
        name: expired
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Berhasil membuat akun trial Vless
          schema:
            allOf:
            - $ref: '#/definitions/dto.SuccessRes'
            - properties:
                data:
                  $ref: '#/definitions/dto.VlessData'
              type: object
        "400":
          description: Bad Request - Payload body tidak valid
          schema:
            $ref: '#/definitions/dto.ErrorRes'
        "422":
          description: Unprocessable Entity - Validasi form gagal
          schema:
            $ref: '#/definitions/dto.ErrorRes'
        "500":
          description: Internal Server Error - Gagal eksekusi ke server
          schema:
            $ref: '#/definitions/dto.ErrorRes'
      security:
      - BearerAuth: []
      summary: Trial Akun Vless
      tags:
      - Trial Akun
  /vps/trial/vmess:
    post:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: Durasi Trial (Menit, maks 1440)
        in: formData
        name: expired
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Berhasil membuat akun trial Vmess
          schema:
            allOf:
            - $ref: '#/definitions/dto.SuccessRes'
            - properties:
                data:
                  $ref: '#/definitions/dto.VmessData'
              type: object
        "400":
          description: Bad Request - Payload body tidak valid
          schema:
            $ref: '#/definitions/dto.ErrorRes'
        "422":
          description: Unprocessable Entity - Validasi form gagal
          schema:
            $ref: '#/definitions/dto.ErrorRes'
        "500":
          description: Internal Server Error - Gagal eksekusi ke server
          schema:
            $ref: '#/definitions/dto.ErrorRes'
      security:
      - BearerAuth: []
      summary: Trial Akun Vmess
      tags:
      - Trial Akun
securityDefinitions:
  BearerAuth:
    description: 'Masukkan token dengan format: Bearer {token}'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
